# Generated by Django 3.0.4 on 2022-11-08 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('institution', models.CharField(default='IET', max_length=100)),
                ('bio', models.TextField(default='...')),
                ('rating', models.IntegerField(default=0)),
                ('hrating', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=1)),
                ('ac_solution', models.IntegerField(default=0)),
                ('wa_solution', models.IntegerField(default=0)),
                ('tle_solution', models.IntegerField(default=0)),
                ('ce_solution', models.IntegerField(default=0)),
                ('re_solution', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
