# Generated by Django 3.0.4 on 2022-11-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='time',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='solution',
            name='verdict',
            field=models.TextField(default='wa'),
        ),
    ]
